-- | This module hierarchy has the example on how to split routes up.
--
-- First, "NestedRouteDispatchSpec.Resources" defines the @resources@ value
-- with 'parseRoutesNoCheck'. This gives us the @['ResourceTree' 'String']@
-- that we need in order to generate the rest of the route information. The
-- 'App' datatype is also defined there, along with the 'RouteOpts' that
-- we'll use for the rest of the code generation.
--
-- Second, "NestedRouteDispatchSpec.Foo.Route" imports the @resources@
-- above and calls @'mkYesodDataOpts' (nestDefaultOptsFor "FooR") "App"
-- resources@. This generates the code for the nested route fragment
-- @FooR@.
--
-- Third, "NestedRouteDispatchSpec.Foo.Handler" imports the @resources@ and
-- the @FooR@ route datatype, and creates the 'YesodDispatchNested'
-- instance. The handlers for the datatype are defined here as well.
-- It also defines the @Authorize FooR@ instance using the application-owned
-- class and result type in "NestedRouteDispatchSpec.Authorization".
-- 'setRouteHandlerWrapper' supplies the matched 'WithParentArgs' and a
-- 'TypedContent' handler to @withAuthorization@, which calls
-- @requireAuthorized route >> handler@.
-- This option belongs on the splice generating the fragment dispatcher,
-- so authorization also runs when testing that fragment directly.
-- Foo also enables named subtree authorization, allowing tests to check its
-- ordering relative to the class-based wrapper. "NestedRouteDispatchSpec.Account.Handler"
-- defines a second fragment with tuple parent arguments and its own wrapper
-- instance, without importing Foo's handlers or authorizers.
--
-- A developer could combine the prior two modules: defining both the route
-- datatype and the handlers for that datatype in the same location. This
-- would eliminate the need to have an orphan instance in the @Handler@
-- module. However, this would require you to know about the implementation
-- of the handlers in order to reference the route fragments, which is not
-- ideal from a module graph compilation perspective.
--
-- Fourth, in "NestedRouteDispatchSpec.YesodData", we define the
-- 'mkYesodDataOpts' for the entire 'App'. Then we can provide the
-- @instance Yesod App@, which is required for running tests. This also
-- gives us instances of 'ToParentRoute' since this is where the full
-- @'Route' App@ is fully defined. This module imports the 'FooR' and
-- 'AccountR' types so they are reused instead of regenerated.
-- The 'Yesod' instance imports no authorizers. Its legacy authorization
-- method records calls and can deny a request, letting tests establish that
-- it still runs before the fragment's named authorizer and wrapper.
--
-- Finally, "NestedRouteDispatchSpec.Foo.HandlerSpec" and
-- "NestedRouteDispatchSpec.Account.HandlerSpec" exercise their fragments
-- through 'YesodDispatchNested'. Each imports @instance Yesod App@ and its
-- own dispatcher, without the whole-site dispatcher or sibling authorizers.
--
-- "NestedRouteDispatchSpec.WholeSiteSpec" separately imports the whole-site
-- dispatcher to check delegation and subsite mounts. "NestedRouteDispatchSpec.InlineSpec"
-- checks flat and inline compatibility dispatch, and
-- "NestedRouteDispatchSpec.AuthorizationTHSpec" checks the public TH API.
-- All specs run in the existing test suite. See the adjacent
-- @NestedRouteDispatchSpec/README.md@ for the authorization regression matrix.
module NestedRouteDispatchSpec where
