resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/23.yaml

packages:
- .

allow-newer: true

extra-deps:
  - git: https://github.com/yesodweb/yesod.git
    commit: bb5998828754a5870077f838e3229d40b09baca3
    subdir: yesod-core
  - encoding-0.10.2
