resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/23.yaml

packages:
- .

allow-newer: true

extra-deps:
  - yesod-core-1.7.0.0
  - encoding-0.10.2
