resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/23.yaml

packages:
- .

extra-deps:
  - git: https://github.com/yesodweb/yesod.git
    commit: 0dda5bf830a4b818697fc08794c17b6f7d68fd62
    subdir: yesod-core
